server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /online {
        proxy_pass http://web-api:3000;
    }
    location /summoners {
        proxy_pass http://web-api:3000;
    }
    location /matches {
        proxy_pass http://web-api:3000;
    }
    location /RSDGames {
        proxy_pass http://web-api:3000;
    }
}